language: python
dist: xenial
python:
  - 2.7
install:
  - pip install zope.testrunner coverage coveralls
  - pip install -e '.[tests]'
script:
  - coverage run -m zope.testrunner --test-path=. -vc
after_script:
  - coverage report -m
  - coveralls
notifications:
  email: false
cache: pip
